Gemma: enabled HPU Graphs and Flash Attention
huggingface/optimum-habana pull request #1173
Opened 2024-07-30 14:10 UTC by dsmertin

# What does this PR do?

This PR fixes HPU Graphs usage and Flash Attention for Gemma model.
Changes are based on Starcoder 2 and Qwen 2 implementations.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

2024-09-06 21:49 UTC, yafshar commented
@dsmertin can you re-base this PR with the main?

2024-09-11 18:28 UTC, imangohari1 requested changes
Hi @dsmertin 
Thank you for this PR. 
Could you please address the followings and push the changes?
- Pls. rebase/sync on top of OH main. Currently 72 commits behind. 
- Pls. make sure to run `make style` 
- Pls. share the results of these gemma before/after these changes. 
- We need to test/update CI tests with these changes.

2024-09-11 20:09 UTC, imangohari1 commented on optimum/habana/transformers/models/gemma/modeling_gemma.py
> +        query_layer = F.pad(query_layer, (0, 0, 0, q_padding), "constant", 0)
make style here complains the F is not defined. 
Pls. take a look.

2024-09-11 20:09 UTC, imangohari1 commented on optimum/habana/transformers/models/gemma/modeling_gemma.py
> +            attention_mask = F.pad(attention_mask, (0, 0, 0, q_padding), "constant", -10000.0)
same here about `make style`

2024-09-11 20:11 UTC, imangohari1 requested changes
I did a bit more testing here and added few more comments. 
this PR also has merge conflict with main. 
Please make sure to address them during the rebase, and `make style`. 
Thanks.

2024-09-11 20:11 UTC, imangohari1 commented on optimum/habana/transformers/models/gemma/modeling_gemma.py
> +            warnings.warn(
make style here complains the `warnings` are not defined. 
shouldn't this be a `logger.warning_once`

2024-09-11 22:26 UTC, imangohari1 requested changes
I fixed some issues and updated the code with `make style` and added `--use_flash_attention` to gemma CI test. 
Please apply the attach fix with `git am < 0001*` and push. 
Thanks. 
[0001-fix-gemma-make-style.-minor-fixes.patch](https://github.com/user-attachments/files/16971015/0001-fix-gemma-make-style.-minor-fixes.patch)

2024-09-16 18:10 UTC, yafshar commented
@dsmertin can you address the comments?

2024-09-17 15:23 UTC, imangohari1 commented
> @yafshar @imangohari1 This PR was created a month and a half ago for different version of the software stack. There was a difference and improvement in performance for this model, but I'm not sure if it's still the case. My colleague told me that there is not much difference for 17.1 version and I need to double check it now. If there'll be no improvement, I'll close it then. Otherwise, I'll go through the comments.

@dsmertin 
Thanks. 
I have tested this PR with the latest release and we would like this PR to be included for the next release. 

Please work through the changes I have suggested here and push them so we can test this further on the RC. 

thanks. 

> I fixed some issues and updated the code with `make style` and added `--use_flash_attention` to gemma CI test. Please apply the attach fix with `git am < 0001*` and push. Thanks. [0001-fix-gemma-make-style.-minor-fixes.patch](https://github.com/user-attachments/files/16971015/0001-fix-gemma-make-style.-minor-fixes.patch)

2024-09-18 16:08 UTC, imangohari1 approved these changes
LGTM!. 
@regisss please take a look. Thanks

2024-09-23 18:52 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum-habana/pr_1173). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-09-23 19:52 UTC, regisss commented
Ci failed with:
```
E     File "/root/workspace/optimum/habana/transformers/models/gemma/modeling_gemma.py", line 552
E       use_cache = use_cache if use_cache is not None else self.config.use_cache
E   IndentationError: unexpected indent
```

2024-09-24 14:55 UTC, regisss commented on optimum/habana/transformers/trainer.py
> +                # attn_softmax_bf16 and use_flash_attention is enabled only for llama, qwen2 and gemma
```suggestion
                # attn_softmax_bf16 and use_flash_attention is enabled only for llama, qwen2, starcoder2 and gemma
```

2024-09-24 14:55 UTC, regisss commented on optimum/habana/transformers/trainer.py
> +            # attn_softmax_bf16 and use_flash_attention are enabled only for llama, qwen2 and gemma
```suggestion
            # attn_softmax_bf16 and use_flash_attention are enabled only for llama, qwen2, starcoder2 and gemma
```

2024-09-24 14:55 UTC, regisss commented on optimum/habana/transformers/generation/utils.py
> +            if self.config.model_type in ["llama", "falcon", "mistral", "qwen2", "starcoder2", "gemma"]:
Why removing GPT-J from this list?

2024-09-24 16:03 UTC, merged