add boft support in stable-diffusion
huggingface/optimum-habana pull request #1295
Opened 2024-08-28 08:50 UTC by sywangyi

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

2024-08-28 08:54 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum-habana/pr_1295). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-09-12 15:17 UTC, imangohari1 commented
Hi @sywangyi 
Thanks for this PR. 
Could you rebase this with OH main and make sure `make style` is applied. 
Please share the results of the CI tests for test_diffusers.py with and without this changes. 
Thanks.

2024-09-13 14:08 UTC, sywangyi commented
same with latest main. 1 case fail

FAILED tests/test_diffusers.py::GaudiStableDiffusionXLImg2ImgPipelineTests::test_stable_diffusion_xl_img2img_euler - AssertionError: 0.21911774845123289 not less than 0.01
================================ 1 failed, 108 passed, 46 skipped, 274 warnings in 776.40s (0:12:56) =================================

2024-09-14 00:17 UTC, imangohari1 requested changes
Hi @sywangyi 
I spent some time on this PR and did some testing:
- I've reworked the README file for a better read. Please apply the changes with the attached patch using `git am < 000*` (**don't copy past the changes, apply the patch please**). 
[0001-fea-dreambooth-reworked-the-readme.patch](https://github.com/user-attachments/files/16999762/0001-fea-dreambooth-reworked-the-readme.patch)

- I've tested the [PEFT example](https://github.com/huggingface/optimum-habana/tree/main/examples/stable-diffusion/training#peft-model-finetune) with both `lora` and `boft`. The lora example finishes in about 6min (`5m47.993s`) but the `boft` one has been running for ~80min and only compeleted 24% (`Steps:  24%|██▎       | 188/800 [1:21:18<3:53:56, 22.94s/it, loss=0.0225, lr=0.0001]`). Any thoughts on why `boft` is so significantly slower than `lora`? Is this bc of lack of hpu graphs? Let's investigate this a bit more. 
   - I've provided the tested `cmd` below. 

```
export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export INSTANCE_DIR="dog"
export CLASS_DIR="path-to-class-images"
export OUTPUT_DIR="out"

logfile=pr1295.$(date -u +%Y%m%d%H%M).$(hostname).log

time python ../../gaudi_spawn.py --world_size 8 --use_mpi train_dreambooth.py   --pretrained_model_name_or_path=$MODEL_NAME    --instance_data_dir=$INSTANCE_DIR   --output_dir=$OUTPUT_DIR   --class_data_dir=$CLASS_DIR   --with_prior_preservation --prior_loss_weight=1.0   --instance_prompt="a photo of sks dog"   --class_prompt="a photo of dog"   --resolution=512   --train_batch_size=1   --num_class_images=200   --gradient_accumulation_steps=1   --learning_rate=1e-4   --lr_scheduler="constant"   --lr_warmup_steps=0   --max_train_steps=800   --mixed_precision=bf16   --use_hpu_graphs_for_training   --use_hpu_graphs_for_inference   --gaudi_config_name Habana/stable-diffusion   lora --unet_r 8 --unet_alpha 8 2>&1 | tee $logfile

time python ../../gaudi_spawn.py --world_size 8 --use_mpi train_dreambooth.py   --pretrained_model_name_or_path=$MODEL_NAME    --instance_data_dir=$INSTANCE_DIR   --output_dir=$OUTPUT_DIR   --class_data_dir=$CLASS_DIR   --with_prior_preservation --prior_loss_weight=1.0   --instance_prompt="a photo of sks dog"   --class_prompt="a photo of dog"   --resolution=512   --train_batch_size=1   --num_class_images=200   --gradient_accumulation_steps=1   --learning_rate=1e-4   --lr_scheduler="constant"   --lr_warmup_steps=0   --max_train_steps=800   --mixed_precision=bf16     --gaudi_config_name Habana/stable-diffusion   boft 2>&1 | tee $logfile
```

2024-09-14 08:29 UTC, sywangyi commented
> Hi @sywangyi I spent some time on this PR and did some testing:
> 
> * I've reworked the README file for a better read. Please apply the changes with the attached patch using `git am < 000*` (**don't copy past the changes, apply the patch please**).
>   [0001-fea-dreambooth-reworked-the-readme.patch](https://github.com/user-attachments/files/16999762/0001-fea-dreambooth-reworked-the-readme.patch)
> * I've tested the [PEFT example](https://github.com/huggingface/optimum-habana/tree/main/examples/stable-diffusion/training#peft-model-finetune) with both `lora` and `boft`. The lora example finishes in about 6min (`5m47.993s`) but the `boft` one has been running for ~80min and only compeleted 24% (`Steps:  24%|██▎       | 188/800 [1:21:18<3:53:56, 22.94s/it, loss=0.0225, lr=0.0001]`). Any thoughts on why `boft` is so significantly slower than `lora`? Is this bc of lack of hpu graphs? Let's investigate this a bit more.
>   
>   * I've provided the tested `cmd` below.
> 
> ```
> export MODEL_NAME="CompVis/stable-diffusion-v1-4"
> export INSTANCE_DIR="dog"
> export CLASS_DIR="path-to-class-images"
> export OUTPUT_DIR="out"
> 
> logfile=pr1295.$(date -u +%Y%m%d%H%M).$(hostname).log
> 
> time python ../../gaudi_spawn.py --world_size 8 --use_mpi train_dreambooth.py   --pretrained_model_name_or_path=$MODEL_NAME    --instance_data_dir=$INSTANCE_DIR   --output_dir=$OUTPUT_DIR   --class_data_dir=$CLASS_DIR   --with_prior_preservation --prior_loss_weight=1.0   --instance_prompt="a photo of sks dog"   --class_prompt="a photo of dog"   --resolution=512   --train_batch_size=1   --num_class_images=200   --gradient_accumulation_steps=1   --learning_rate=1e-4   --lr_scheduler="constant"   --lr_warmup_steps=0   --max_train_steps=800   --mixed_precision=bf16   --use_hpu_graphs_for_training   --use_hpu_graphs_for_inference   --gaudi_config_name Habana/stable-diffusion   lora --unet_r 8 --unet_alpha 8 2>&1 | tee $logfile
> 
> time python ../../gaudi_spawn.py --world_size 8 --use_mpi train_dreambooth.py   --pretrained_model_name_or_path=$MODEL_NAME    --instance_data_dir=$INSTANCE_DIR   --output_dir=$OUTPUT_DIR   --class_data_dir=$CLASS_DIR   --with_prior_preservation --prior_loss_weight=1.0   --instance_prompt="a photo of sks dog"   --class_prompt="a photo of dog"   --resolution=512   --train_batch_size=1   --num_class_images=200   --gradient_accumulation_steps=1   --learning_rate=1e-4   --lr_scheduler="constant"   --lr_warmup_steps=0   --max_train_steps=800   --mixed_precision=bf16     --gaudi_config_name Habana/stable-diffusion   boft 2>&1 | tee $logfile
> ```

yes. I have file a bug to pytorch training team about the perf issue, will cc you in the jira

2024-09-17 15:21 UTC, imangohari1 commented
Overal LGTM although there is a performance issue with boft. Thanks @sywangyi 
@regisss how do you suggest we proceed?

2024-09-18 21:05 UTC, libinta commented
@sywangyi  please test with latest synapse SW, if there is still issue, we dont need to merge this change for next synapse release as it's not functional

2024-09-18 23:10 UTC, sywangyi commented
> @sywangyi please test with latest synapse SW, if there is still issue, we dont need to merge this change for next synapse release as it's not functional

which version do you mean, I think habana pytorch training team is still working on it.

2024-09-20 20:18 UTC, imangohari1 commented
> > @sywangyi please test with latest synapse SW, if there is still issue, we dont need to merge this change for next synapse release as it's not functional
> 
> which version do you mean? I think habana pytorch training team is still working on it.

@sywangyi  1.18.0 release build id 410.

2024-09-24 22:02 UTC, libinta commented
@sywangyi  do you have test result?

2024-09-25 06:51 UTC, kaixuanliu commented
> @sywangyi do you have test result?

@libinta , Hi, we do not have env for 1.18.0 with build 410, but @yeonsily gave me a docker image with build 438, can we use it to have a test? The env for this docker image is:
```
habana-torch-dataloader 1.18.0.438
habana-torch-plugin     1.18.0.438
pytorch-lightning       2.4.0
torch                   2.4.0a0+git74cd574
torch_tb_profiler       0.4.0
torchaudio              2.4.0a0+69d4077
torchdata               0.7.1+5e6f7b7
torchmetrics            1.4.2
torchsde                0.2.6
torchtext               0.18.0a0+9bed85d
torchvision             0.19.0a0+48b1edf
```

2024-09-26 01:53 UTC, kaixuanliu commented
> @sywangyi do you have test result?

Hi, @libinta , we used a docker image with build 438 for 1.18.0 release from @yeonsily and have a test. The perf of boft is still significantly slower than lora, for single card finetune, lora takes ~4min 30s, while boft needs more than 2 hours.

2024-09-26 16:32 UTC, imangohari1 commented
> > @sywangyi do you have test result?
> 
> Hi, @libinta , we used a docker image with build 438 for 1.18.0 release from @yeonsily and have a test. The perf of boft is still significantly slower than lora, for single card finetune, lora takes ~4min 30s, while boft needs more than 2 hours.

I have tested this with driver 1.18.0-460 and the corresponding docker. It still shows the same behavior. 
Our team is looking at rewriting the code that is causing recompile.

2024-11-11 07:55 UTC, yao-matrix commented
> > > @sywangyi do you have test result?
> > 
> > 
> > Hi, @libinta , we used a docker image with build 438 for 1.18.0 release from @yeonsily and have a test. The perf of boft is still significantly slower than lora, for single card finetune, lora takes ~4min 30s, while boft needs more than 2 hours.
> 
> I have tested this with driver 1.18.0-460 and the corresponding docker. It still shows the same behavior. Our team is looking at rewriting the code that is causing recompile.

@imangohari1 , do we have update on this?

2024-11-12 04:28 UTC, imangohari1 commented
> > > > @sywangyi do you have test result?
> > > 
> > > 
> > > Hi, @libinta , we used a docker image with build 438 for 1.18.0 release from @yeonsily and have a test. The perf of boft is still significantly slower than lora, for single card finetune, lora takes ~4min 30s, while boft needs more than 2 hours.
> > 
> > 
> > I have tested this with driver 1.18.0-460 and the corresponding docker. It still shows the same behavior. Our team is looking at rewriting the code that is causing recompile.
> 
> @imangohari1 , do we have update on this?

I am not if the issue is resolved or not. 
@sywangyi WDYT?

2024-11-12 05:04 UTC, sywangyi commented
according to https://habana.atlassian.net/browse/HS-3208, it has not been resolved yet

2025-01-14 13:46 UTC, Luca-Calabria commented
Update: RnD guys said the new feature is targeted for release 1.21.0

2025-03-21 09:21 UTC, Luca-Calabria commented
The fix is under PR review, I'll test it when it is ready

2025-04-01 11:26 UTC, Luca-Calabria commented
@sywangyi the build with the fix is ready 1.21.0-376. I tested it. Please check the ticket for all the details.

2025-04-07 07:54 UTC, Luca-Calabria commented
@sywangyi let me try again. In my test removing .cpu() from all the three orth_rotate_butterfly.squeeze(0).cpu() and running lazy mode I registrered 7 minutes to complete 1 epoch with 10 classes. 
Anyway the build 1.21.376 need explicit PT_HPU_LAZY_MODE=1 to run Lazy

2025-04-07 10:08 UTC, Luca-Calabria commented
@sywangyi I'm not sure what is happening in your case but I'm able to run multiple epochs
![image](https://github.com/user-attachments/assets/992acf03-6294-47db-9717-693b9212abb2)

2025-04-08 02:36 UTC, sywangyi commented
yes, 32min in my env, is the perf expected?

2025-04-29 02:00 UTC, sywangyi commented
@libinta  will we merge the PR in 1.21, since 1.21 fix the the slow compilation when "torch.block_diag" operation run

2025-06-26 13:55 UTC, regisss commented
Does this PR work with Synapse 1.21?

2025-06-27 01:21 UTC, sywangyi commented
> Does this PR work with Synapse 1.21?

yes

2025-07-03 06:54 UTC, yao-matrix commented
@regisss , maybe we can merge it? Since it works on 1.21 and it's a 10-month journey w/ times of rebase.

2025-07-07 14:04 UTC, regisss commented on tests/test_diffusers.py
> +            # WA torch.inverse issue in Synapse AI 1.17 for oft and boft
Do we still need this?

2025-07-07 14:04 UTC, regisss commented on examples/stable-diffusion/text_to_image_generation.py
> +                        # WA torch.inverse issue in Synapse AI 1.17 for oft and boft
Do we still need this?

2025-07-07 14:04 UTC, regisss commented on examples/stable-diffusion/text_to_image_generation.py
> +                        # WA torch.inverse issue in Synapse AI 1.17 for oft and boft
Same

2025-07-07 15:01 UTC, Luca-Calabria commented
@sywangyi it seems there is an incompatibility with numpy >2.0, which seems the version used now.
```
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 400, in __getattr__
[rank0]:     raise AttributeError(
[rank0]: AttributeError: `np.string_` was removed in the NumPy 2.0 release. Use `np.bytes_` instead.
```
Maybe it is solved in the last main commit? Please merge again the main branch to check this.

2025-07-10 11:14 UTC, sywangyi commented
> @sywangyi it seems there is an incompatibility with numpy >2.0, which seems the version used now.
> 
> ```
> [rank0]:   File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 400, in __getattr__
> [rank0]:     raise AttributeError(
> [rank0]: AttributeError: `np.string_` was removed in the NumPy 2.0 release. Use `np.bytes_` instead.
> ```
> 
> Maybe it is solved in the last main commit? Please merge again the main branch to check this.

resovled by upgrade tensorboard

2025-07-10 14:05 UTC, regisss reviewed
It looks good to me. Can you also check that the Diffusers CI passes please? CI is offline and I don't have access to any Gaudi server at the moment.

2025-07-10 14:05 UTC, regisss commented on examples/stable-diffusion/text_to_image_generation.py
> +                        pipeline.unet = pipeline.unet.merge_and_unload()
I'm curious, autocast has an impact on merge_and_unload ?

2025-07-11 00:29 UTC, sywangyi commented
> It looks good to me. Can you also check that the Diffusers CI passes please? CI is offline and I don't have access to any Gaudi server at the moment.

I check the GaudiStableDiffusionPipelineTester and DreamBooth test which is diffuser+peft test, ALL could pass.

2025-07-11 02:42 UTC, sywangyi commented on examples/stable-diffusion/text_to_image_generation.py
> +                        pipeline.unet = pipeline.unet.merge_and_unload()
has impact on oft in lazy model, remove the autocast will lead to "RuntimeError: Graph compile failed. synStatus=synStatus 26 [Generic failure]"

2025-07-11 09:51 UTC, merged