Qwen2 moe
huggingface/optimum-habana pull request #1316
Opened 2024-09-05 10:10 UTC by gyou2021

Added Qwen2-MoE model into optimum-habana, optimizing its performance on Gaudi with kv_cache, reuse_cache, flash attention, internal bucket, etc.

Test command:

cd optimum-habana

python -m pytest tests/test_text_generation_example.py -v -s

cd examples/text-generation/

python run_generation.py --model_name_or_path --use_hpu_graphs --use_kv_cache --reuse_cache --trim_logits --attn_softmax_bf16 --use_flash_attention --max_input_tokens 256 --max_new_tokens 256 --batch_size 2 --limit_hpu_graphs --bucket_size 128 --bucket_internal --n_iterations 2 --warmup 2 --bf16

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you make sure to update the documentation with your changes?
- [X] Did you write any new necessary tests?

2024-09-06 07:33 UTC, gyou2021 commented
@ssarkar2 I added Qwen2-MoE test code in test_text_generation_example.py according to your comments in https://github.com/huggingface/optimum-habana/pull/1162. What's more, I created a new branch qwen2-moe following the guidance of https://github.com/huggingface/optimum/blob/main/CONTRIBUTING.md. Thank you.

2024-09-11 21:31 UTC, imangohari1 requested changes
Hi @gyou2021 
Thank you for this PR. 
I have gone through this and the the tests seem running fine. 
I made a change in CI tests since `Qwen1.5-7B` was already there, and instead added the Qwen2-7B. 

Please apply the patch with `git am < 0001*` and push. 
We review afterwards. 
Thanks. 
[0001-fea-ci-Added-qwen2-7b-bs-512.patch](https://github.com/user-attachments/files/16970632/0001-fea-ci-Added-qwen2-7b-bs-512.patch)

2024-09-12 07:51 UTC, gyou2021 commented
Hi @imangohari1 

Thank you for your comments.

I added Qwen2-7B test and removed repeated Qwen1.5-7B test in tests/test_text_generation_example.py according to 0001-fea-ci-Added-qwen2-7b-bs-512.patch. Since "error: tests/test_text_generation_example.py: does not match index" showed when I ran git am < 0001* to apply the patch, I manually modified the code and push it. 

> Hi @gyou2021 Thank you for this PR. I have gone through this and the the tests seem running fine. I made a change in CI tests since `Qwen1.5-7B` was already there, and instead added the Qwen2-7B.
> 
> Please apply the patch with `git am < 0001*` and push. We review afterwards. Thanks. [0001-fea-ci-Added-qwen2-7b-bs-512.patch](https://github.com/user-attachments/files/16970632/0001-fea-ci-Added-qwen2-7b-bs-512.patch)

2024-09-12 20:01 UTC, imangohari1 approved these changes
LGTM! 
I have tested these changes with local cmd and CI. 
they appear functional. 

This PR has also been tested via a Integration branch https://github.com/huggingface/optimum-habana/compare/main...imangohari1:optimum-habana:ig/ci_20240911?expand=1 (CI#255) and they have not introduced a regression. 

@regisss  please take a look when you had a chance.

2024-09-24 15:45 UTC, regisss reviewed
There are quite a lot of commented code in the modeling file, can you clean that a bit please?

2024-09-25 20:25 UTC, imangohari1 commented
@gyou2021 Can you please address Regiss comments? Tnx

2024-09-26 09:48 UTC, gyou2021 commented on README.md
> +| Qwen2-MoE |   | <div style="text-align:left"><li>Single card</li></div> | <li>[text generation](https://github.com/huggingface/optimum-habana/tree/main/examples/text-generation)</li> |
> Can you add the same in
> 
> https://github.com/huggingface/optimum-habana/blob/091c8a52655eb35a3feaea93b4b3d98b1f6551fc/docs/source/index.mdx?plain=1#L59
> 
> please?
Added. 
Thank you for your comment.

2024-09-26 09:49 UTC, gyou2021 commented on README.md
> +| Qwen2-MoE |   | <div style="text-align:left"><li>Single card</li></div> | <li>[text generation](https://github.com/huggingface/optimum-habana/tree/main/examples/text-generation)</li> |
> Can you add the same in
> 
> https://github.com/huggingface/optimum-habana/blob/091c8a52655eb35a3feaea93b4b3d98b1f6551fc/docs/source/index.mdx?plain=1#L59
> 
> please?

Added.
Thank you for your comment.

2024-09-26 15:41 UTC, gyou2021 commented
> There are quite a lot of commented code in the modeling file, can you clean that a bit please?
Thank you for your comment.
The code has been cleaned.

2024-09-26 15:41 UTC, gyou2021 commented
> @gyou2021 Can you please address Regiss comments? Tnx

Sure. Done.

2024-09-30 21:42 UTC, regisss commented
@gyou2021 There are merge conflicts to solve

2024-10-03 14:52 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum-habana/pr_1316). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-10-03 15:20 UTC, regisss approved these changes

2024-10-03 15:20 UTC, merged

2024-10-04 04:27 UTC, gyou2021 commented
> @gyou2021 There are merge conflicts to solve edit: solved

Thank you.