add README.md for Sentence transformer examples with HPU device
huggingface/optimum-habana pull request #1355
Opened 2024-09-24 16:24 UTC by ZhengHongming888

# What does this PR do?

This PR will add one README.md for all sentence transformer HPU examples although they have each readme on how to run for each example. This README will give the whole pictures on all examples for sentence transformer with HPU device and their supported features/test configurations as below like :

![image](https://github.com/user-attachments/assets/084d02f7-7660-4958-b338-54fdfc4009b6)

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

2024-09-24 20:39 UTC, hchauhan123 requested changes

2024-09-24 20:39 UTC, hchauhan123 commented on examples/sentence-transformers-training/README.md
> +- **[training_stsbenchmark.py](https://github.com/huggingface/optimum-habana/tree/main/examples/sentence-transformers-training/sts)** - This example shows how to create a SentenceTransformer model fr
*Sentence Transformers

2024-09-24 20:39 UTC, hchauhan123 commented on examples/sentence-transformers-training/README.md
> +- **[training_nli.py](https://github.com/huggingface/optimum-habana/tree/main/examples/sentence-transformers-training/nli)** - This example gives two sentences (premise and hypothesis) and the task o
```suggestion
- **[training_nli.py](https://github.com/huggingface/optimum-habana/tree/main/examples/sentence-transformers-training/nli)** - This example provides two sentences (a premise and a hypothesis), and the task of Natural Language Inference (NLI) is to determine whether the premise entails the hypothesis, contradicts it, or if they are neutral. Commonly the NLI dataset in [SNLI](https://huggingface.co/datasets/stanfordnlp/snli) and [MultiNLI](https://huggingface.co/datasets/nyu-mll/multi_nli) are used.
```

2024-09-24 21:49 UTC, libinta commented on examples/sentence-transformers-training/README.md
> +We provide 3 examples to show how to use the Sentence Transformers with HPU devices.
Gaudi

2024-09-24 22:41 UTC, ZhengHongming888 commented on examples/sentence-transformers-training/README.md
> +- **[training_stsbenchmark.py](https://github.com/huggingface/optimum-habana/tree/main/examples/sentence-transformers-training/sts)** - This example shows how to create a SentenceTransformer model fr
done!

2024-09-24 23:42 UTC, hchauhan123 approved these changes

2024-10-02 20:21 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum-habana/pr_1355). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-10-02 20:25 UTC, regisss approved these changes

2024-10-02 20:56 UTC, merged