Optimizations and WAs to support HPU execution for Detr-Resnet-50
huggingface/optimum-habana pull request #1404
Opened 2024-10-08 16:23 UTC by splotnikv

# What does this PR do?

This is rebased and updated https://github.com/huggingface/optimum-habana/pull/1334

2024-10-15 23:52 UTC, vidyasiv requested changes
Will be making another pass

2024-10-15 23:52 UTC, vidyasiv commented on tests/test_object_detection.py
> +            print(f"boxes = {boxes}")
please remove debug print, it might be more meaningful if added as part of the assertLess(first, second, msg="<your message on boxes value>")

2024-10-22 23:13 UTC, sandeep-maddipatla commented on tests/test_object_detection.py
> +    def get_expected_num_boxes(self):
Hi @vidyasiv - Sorry, I couldn't follow this comment. Can you please elaborate on what is expected here? 

The code is attempting to add a test for this model by hard-coding the co-ordinates expected for a particular image in coco dataset, and checking if the detected bboxes are within a 1% tolerance limit. It extends a pre-existing class to reuse some of its functions.

2024-10-23 17:16 UTC, vidyasiv commented on tests/test_object_detection.py
> +    def get_expected_num_boxes(self):
What are we testing if we return 5 every time? You can have a function or constant if its an intermediate value for another test.

2024-10-23 18:19 UTC, sandeep-maddipatla commented on tests/test_object_detection.py
> +    def get_expected_num_boxes(self):
So, this follows the pre-existing object detection test in [optimum-habana](https://github.com/huggingface/optimum-habana/blob/main/tests/test_object_detection.py). It tests inference with a [single image ](http://images.cocodataset.org/val2017/000000039769.jpg) against a reference result from the model: the result should get us a number of bounding boxes (5 for the image used), their co-ordinates and classification. The test checks if the model under test is detecting all boxes and validates if the first box is within a certain error margin. 

I reorganized the original test code a little bit to reuse the same test_* functions for the model we are adding here, while allowing for different reference results depending on the model. Each test class now has its own `get_expected_loc` and `get_expected_num_boxes` helper functions capturing reference results for the model the class covers.  Note that these functions are not recognized as unit tests in the `TestCase` class implementation.

The idea was we modify/extend these helper functions when we want to add more tests/images

2024-10-23 18:51 UTC, vidyasiv commented on tests/test_object_detection.py
> +    def get_expected_num_boxes(self):
consider this resolved please

2024-10-23 22:43 UTC, vidyasiv commented
@sandeep-maddipatla  now that you're back you want to continue this PR or go back to 1334? I am going to start testing soon so let me know your preference

2024-10-23 23:27 UTC, sandeep-maddipatla commented
> @sandeep-maddipatla now that you're back you want to continue this PR or go back to 1334? I am going to start testing soon so let me know your preference

Hi @vidyasiv - If it is all the same to you, I'd prefer to move to #1334 .. I'll need to pull these changes there (expected to be EoD).

2024-10-23 23:54 UTC, vidyasiv commented
> > @sandeep-maddipatla now that you're back you want to continue this PR or go back to 1334? I am going to start testing soon so let me know your preference
> 
> Hi @vidyasiv - If it is all the same to you, I'd prefer to move to #1334 .. I'll need to pull these changes there (expected to be EoD).

Sure no problem, take your time. Once you've moved over, this PR can be closed to avoid confusion.

2024-10-24 19:20 UTC, sandeep-maddipatla commented
Addressed review feedback and merged in changes into #1334 ... Will use that PR to continue the review process.

2024-10-31 20:32 UTC, vidyasiv commented
@splotnikv , i think we can close this review, thanks

2024-11-04 21:43 UTC, closed without merging