add cogvideox support for gaudi.
huggingface/optimum-habana pull request #1600
Opened 2024-12-12 09:07 UTC by nc-BobLee

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

2024-12-12 09:31 UTC, nc-BobLee commented
test command：python cogvideo_generate.py --model_name_or_path /mnt/disk2/libo/hf_models/CogVideoX-2b/  --output_name   
 panda_gaudi.mp4
output video：

2024-12-12 09:32 UTC, nc-BobLee commented
https://github.com/user-attachments/assets/917511eb-9878-433e-96cc-37242c8e563c

2025-01-07 16:26 UTC, shepark commented on examples/text-to-video/README.md
> +python3 cogvideo_generate.py \
typo
```suggestion
python3 cogvideox_generate.py \
```

2025-01-07 16:46 UTC, shepark commented on examples/text-to-video/README.md
> +    --model_name_or_path CogVideoX-2b \
Why don't you keep the same pattern for assigning model name? or make the default path working with original change?
```suggestion
    --model_name_or_path THUDM/CogVideoX-2b \
```

2025-01-09 23:29 UTC, shepark commented on examples/text-to-video/README.md
> +    --model_name_or_path CogVideoX-2b \
@nc-BobLee can you update PR?

2025-01-13 02:55 UTC, nc-BobLee commented on examples/text-to-video/README.md
> +    --model_name_or_path CogVideoX-2b \
the PR has been updated.

2025-01-17 09:36 UTC, nc-BobLee commented
could you please help to review my change @shepark 
thanks!

2025-01-18 00:46 UTC, shepark commented
> could you please help to review my change @shepark thanks!

I sent email to you, please response it. thanks.

2025-01-18 00:46 UTC, shepark approved these changes

2025-01-23 02:29 UTC, Wei-Lin-Intel commented
Hi @regisss , could you please help to review this PR? Thanks!

2025-01-23 21:11 UTC, dsocek requested changes
See comments for requested changes.   Also, please run `make style` to fix code formatting

2025-02-06 10:33 UTC, astachowiczhabana commented
@regisss @nc-BobLee can we merge this change?

2025-02-06 13:39 UTC, dsocek commented
> @regisss @nc-BobLee can we merge this change?

@nc-BobLee  can you, please, address some of the requested changes?

2025-02-11 10:42 UTC, nc-BobLee commented
> > @regisss @nc-BobLee can we merge this change?
> 
> @nc-BobLee can you, please, address some of the requested changes?

I have addressed the requested changes. please help to review.

2025-02-21 06:28 UTC, nc-BobLee commented on examples/text-to-video/cogvideox_generate.py
> +import argparse
this file has been  removed.

2025-02-21 06:29 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/cogvideoX_gaudi.py
> +from typing import Any, Dict, Optional, Tuple, Union
this file has been removed.

2025-02-21 06:30 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/cogvideoX_gaudi.py
> +class AutoencoderKLCogVideoXGaudi(AutoencoderKLCogVideoX):
file and function removed.

2025-02-21 06:30 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/cogvideoX_gaudi.py
> +class CogVideoXCausalConv3dGaudi(nn.Module):
function removed.

2025-02-21 06:31 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox_gaudi.py
> +def retrieve_timesteps(
this is for cogvideoX model does not copy.

2025-02-21 06:32 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox_gaudi.py
> +class time_box_t():
removed.

2025-02-21 06:46 UTC, nc-BobLee commented on tests/test_diffusers.py
> +        assert 49 == len(video)
done.

2025-02-21 06:46 UTC, nc-BobLee commented on tests/test_diffusers.py
> +        assert video is not None
done.

2025-02-21 15:06 UTC, dsocek approved these changes
Thanks for addressing the requested changes.   Please rebase and resolve conflicts and run `make style` to fix code formatting.

2025-02-24 06:59 UTC, Wei-Lin-Intel commented
@regisss  Please help to review the changes. All the codes are updated now. Thanks!

2025-03-18 03:20 UTC, nc-BobLee commented
Please help to review the changes.  @regisss

2025-03-26 16:11 UTC, libinta commented
@nc-BobLee  can you recheck the changes on transformers_future branch as we are in the release phase for transformers4.49

2025-03-27 07:11 UTC, nc-BobLee commented
> @nc-BobLee can you recheck the changes on transformers_future branch as we are in the release phase for transformers4.49

test with transformers_future branch, cogvideoX pipe run ok.
![image](https://github.com/user-attachments/assets/4062ac42-3b5f-42ed-9514-4d1cd5f7fdb8)

2025-04-17 15:33 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox_gaudi.py
> +# Copyright 2023 The HuggingFace Team. All rights reserved.
Yes, no need to add `_gaudi` at the end of the filename

2025-04-17 15:33 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox_gaudi.py
> +    frames: torch.Tensor
It's exactly the same as https://github.com/huggingface/diffusers/blob/4397f59a37012054212603a8dc8ba9db58f8a56c/src/diffusers/pipelines/cogvideo/pipeline_output.py#L9, let's import it directly here instead of duplicating code

2025-04-17 15:33 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox_gaudi.py
> +class CogVideoXAttnProcessorGaudi:
Can you put a link to the source?

2025-04-17 15:33 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox_gaudi.py
> +def cogvideoXTransformerForwardGaudi(
Same

2025-04-17 15:33 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox_gaudi.py
> +def tiled_decode_gaudi(self, z: torch.Tensor, return_dict: bool = True) -> Union[DecoderOutput, torch.Tensor]:
Same

2025-04-17 15:33 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox_gaudi.py
> +def CogVideoXCausalConv3dforwardGaudi(
Same

2025-04-17 15:33 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox_gaudi.py
> +def retrieve_timesteps(
I agree with @dsocek, it's exactly the same as https://github.com/huggingface/diffusers/blob/4397f59a37012054212603a8dc8ba9db58f8a56c/src/diffusers/pipelines/cogvideo/pipeline_cogvideox.py#L88, let's import it here and avoid duplicating code

2025-04-18 03:25 UTC, nc-BobLee commented on examples/video-comprehension/run_example.py
> +        help="pipeline type:sdp or cogvideoX",
changed to video_llava

2025-04-18 09:32 UTC, nc-BobLee commented on examples/video-comprehension/README.md
> +
resolved.

2025-04-18 09:33 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox_gaudi.py
> +class CogVideoXAttnProcessorGaudi:
resolved.

2025-04-18 09:33 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox_gaudi.py
> +def cogvideoXTransformerForwardGaudi(
resolved.

2025-04-18 09:34 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox_gaudi.py
> +def tiled_decode_gaudi(self, z: torch.Tensor, return_dict: bool = True) -> Union[DecoderOutput, torch.Tensor]:
resolved.

2025-04-18 09:34 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox_gaudi.py
> +def CogVideoXCausalConv3dforwardGaudi(
resolved.

2025-04-18 10:05 UTC, nc-BobLee commented
all comments have been resolved, please help to review the changes. @regisss

2025-04-18 12:28 UTC, regisss commented on examples/stable-diffusion/README.md
> +    --model_name_or_path "/mnt/disk2/libo/hf_models/CogVideoX-2b/" \
```suggestion
    --model_name_or_path THUDM/CogVideoX-2b \
```

2025-04-18 12:28 UTC, regisss commented on examples/stable-diffusion/text_to_video_generation.py
> +        nargs="*",
I dont think we need nargs here

2025-04-18 12:28 UTC, regisss commented on examples/stable-diffusion/text_to_video_generation.py
> +        help="pipeline type:sdp or cogvideoX",
```suggestion
        default="stable_diffusion",
        help="pipeline type: stable_diffusion or cogvideoX",
```
I still find sdp not very explicit

2025-04-18 12:28 UTC, regisss commented on examples/stable-diffusion/text_to_video_generation.py
> +    if args.pipeline_type[0] == "sdp":
```suggestion
    if args.pipeline_type == "stable_diffusion":
```
No need for [0] if we don't use nargs anymore

2025-04-18 12:28 UTC, regisss commented on examples/stable-diffusion/text_to_video_generation.py
> +    elif args.pipeline_type[0] == "cogvideox":
```suggestion
    elif args.pipeline_type == "cogvideox":
```

2025-04-18 12:28 UTC, regisss commented on examples/stable-diffusion/text_to_video_generation.py
> +    if args.pipeline_type[0] == "sdp":
```suggestion
    if args.pipeline_type == "stable_diffusion":
```

2025-04-18 12:28 UTC, regisss commented on examples/stable-diffusion/text_to_video_generation.py
> +    elif args.pipeline_type[0] == "cogvideox":
```suggestion
    elif args.pipeline_type == "cogvideox":
```

2025-04-18 12:28 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +    frames: torch.Tensor
Why not importing directly https://github.com/huggingface/diffusers/blob/bbd0c161b55ba2234304f1e6325832dd69c60565/src/diffusers/pipelines/cogvideo/pipeline_output.py#L9 ?

2025-04-18 12:28 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +        bf16_full_eval: bool = False,
We need to add `sdp_on_bf16`

2025-04-18 12:28 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +            bf16_full_eval,
Same

2025-04-18 12:28 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +    Adapted from: https://github.com/huggingface/diffusers/blob/v0.31.0/src/diffusers/models/embeddings.py#L697
Let's put it in https://github.com/huggingface/optimum-habana/tree/main/optimum/habana/diffusers/models in a new `embeddings.py` file. I know it's a bit annoying that makes maintenance easier as this replicates the arborescence of the Diffusers library.

2025-04-18 12:28 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +    Adapted from: https://github.com/huggingface/diffusers/blob/v0.31.0/src/diffusers/models/attention_processor.py#L1896
Let's move this class to https://github.com/huggingface/optimum-habana/blob/main/optimum/habana/diffusers/models/attention_processor.py

2025-04-18 12:28 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +    Adapted from: https://github.com/huggingface/diffusers/blob/v0.31.0/src/diffusers/models/transformers/cogvideox_transformer_3d.py#L408
Let's move this to https://github.com/huggingface/optimum-habana/tree/main/optimum/habana/diffusers/models in a new `transformers/cogvideox_transformer_3d.py` file please

2025-04-18 12:28 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +    Adapted from: https://github.com/huggingface/diffusers/blob/v0.31.0/src/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py#L1374
Let's move this to https://github.com/huggingface/optimum-habana/tree/main/optimum/habana/diffusers/models in a new `autoencoders/autoencoder_kl_cogvideox.py` file please

2025-04-18 12:28 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +    Adapted from: https://github.com/huggingface/diffusers/blob/v0.31.0/src/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py#L129
Same

2025-04-21 07:54 UTC, nc-BobLee commented on examples/stable-diffusion/README.md
> +    --model_name_or_path "/mnt/disk2/libo/hf_models/CogVideoX-2b/" \
resolved

2025-04-21 07:54 UTC, nc-BobLee commented on examples/stable-diffusion/text_to_video_generation.py
> +        help="pipeline type:sdp or cogvideoX",
resolved

2025-04-21 07:54 UTC, nc-BobLee commented on examples/stable-diffusion/text_to_video_generation.py
> +    elif args.pipeline_type[0] == "cogvideox":
resolved

2025-04-21 07:54 UTC, nc-BobLee commented on examples/stable-diffusion/text_to_video_generation.py
> +    elif args.pipeline_type[0] == "cogvideox":
resolved

2025-04-21 07:55 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +        bf16_full_eval: bool = False,
resolved

2025-04-21 07:55 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +    Adapted from: https://github.com/huggingface/diffusers/blob/v0.31.0/src/diffusers/models/embeddings.py#L697
resolved

2025-04-21 07:58 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +    Adapted from: https://github.com/huggingface/diffusers/blob/v0.31.0/src/diffusers/models/attention_processor.py#L1896
resolved

2025-04-21 07:58 UTC, nc-BobLee commented on examples/stable-diffusion/text_to_video_generation.py
> +        nargs="*",
resolved

2025-04-21 07:59 UTC, nc-BobLee commented on examples/stable-diffusion/text_to_video_generation.py
> +    if args.pipeline_type[0] == "sdp":
resolved

2025-04-21 07:59 UTC, nc-BobLee commented on examples/stable-diffusion/text_to_video_generation.py
> +    if args.pipeline_type[0] == "sdp":
resolved

2025-04-21 07:59 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +    frames: torch.Tensor
resolved

2025-04-21 07:59 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +    Adapted from: https://github.com/huggingface/diffusers/blob/v0.31.0/src/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py#L1374
resolved

2025-04-21 07:59 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +    Adapted from: https://github.com/huggingface/diffusers/blob/v0.31.0/src/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py#L129
resolved

2025-04-21 08:00 UTC, nc-BobLee commented
all comments resolved, please help to review the changes again. @regisss

2025-04-22 08:42 UTC, regisss reviewed
I left a few additional comments. After these are addressed, we should be good :slightly_smiling_face:

2025-04-22 08:42 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +from optimum.habana.transformers.gaudi_configuration import GaudiConfig
```suggestion
from ...models.attention_processor import CogVideoXAttnProcessorGaudi
from ...models.cogvideox_transformer_3d import cogvideoXTransformerForwardGaudi
from ...models.autoencoders.autoencoder_kl_cogvideox import tiled_decode_gaudi, CogVideoXCausalConv3dforwardGaudi
from ..pipeline_utils import GaudiDiffusionPipeline
from ....transformers.gaudi_configuration import GaudiConfig
```
Let's use relative imports to stay consistent with the rest of the codebase. Absolute imports  can sometimes lead to weird behaviours when two versions of the lib are installed in two different places.

2025-04-22 08:42 UTC, regisss commented on optimum/habana/diffusers/models/attention_processor.py
> +from optimum.habana.diffusers.models.embeddings import apply_rotary_emb
```suggestion
from .embeddings import apply_rotary_emb
```

2025-04-22 08:42 UTC, regisss commented on optimum/habana/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py
> +
Not sure why there are so many empty lines here, please run `make style`

2025-04-22 08:42 UTC, regisss commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +        return self._interrupt
These should be inherited from `CogVideoXPipeline`, I don't think we need them

2025-04-22 09:55 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +from optimum.habana.transformers.gaudi_configuration import GaudiConfig
resolved

2025-04-22 09:55 UTC, nc-BobLee commented on optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
> +        return self._interrupt
resolved

2025-04-22 09:55 UTC, nc-BobLee commented on optimum/habana/diffusers/models/attention_processor.py
> +from optimum.habana.diffusers.models.embeddings import apply_rotary_emb
resolved

2025-04-22 09:55 UTC, nc-BobLee commented on optimum/habana/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py
> +
resolved

2025-04-22 09:58 UTC, nc-BobLee commented
Additional comments have been addressed, please review.

2025-04-22 14:01 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum-habana/pr_1600). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2025-04-22 14:37 UTC, regisss commented
@nc-BobLee It seems `tests/test_diffusers.py::GaudiCogVideoXPipelineTester::test_cogvideoX_default_case` failed in CI.

Can you also run `make style` to make the code format check pass please?

2025-04-23 09:50 UTC, nc-BobLee commented
run make style to make code format check pass, and resolved ci test failed issue. please help to review. @regisss

2025-04-23 20:36 UTC, regisss approved these changes
LGTM

2025-04-23 20:36 UTC, merged