fix FlUX.1_dev guidance_batches bug for pad case in _split_inputs_int…
huggingface/optimum-habana pull request #1607
Opened 2024-12-13 08:54 UTC by huijuanzh

…o_batches

# What does this PR do?

Fixes # (issue)
https://habana.atlassian.net/browse/CS-864 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

runtime error when num_images_per_prompt is not divisible by batch_size .
test cmd:
python text_to_image_generation.py     --model_name_or_path /nfs_home/data/FLUX.1-dev     --prompts "A cat holding a sign that says hello world"     --num_images_per_prompt 10     --batch_size 4     --num_inference_steps 4     --image_save_dir /tmp/flux_1_images     --scheduler flow_match_euler_discrete    --use_habana     --use_hpu_graphs     --gaudi_config Habana/stable-diffusion     --bf16

Traceback (most recent call last):
  File "/host/mnt/ctrl/disk1/personal/huijuanz/ws/optimum-habana/examples/stable-diffusion/text_to_image_generation.py", line 699, in <module>
    main()
  File "/host/mnt/ctrl/disk1/personal/huijuanz/ws/optimum-habana/examples/stable-diffusion/text_to_image_generation.py", line 662, in main
    outputs = pipeline(prompt=args.prompts, **kwargs_call)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/host/mnt/ctrl/disk1/personal/huijuanz/ws/optimum-habana/optimum/habana/diffusers/pipelines/flux/pipeline_flux.py", line 638, in __call__
    ) = self._split_inputs_into_batches(batch_size, latents, prompt_embeds, pooled_prompt_embeds, guidance)
  File "/host/mnt/ctrl/disk1/personal/huijuanz/ws/optimum-habana/optimum/habana/diffusers/pipelines/flux/pipeline_flux.py", line 371, in _split_inputs_into_batches
    sequence_to_stack = (guidance_batches[-1],) + tuple(
  File "/host/mnt/ctrl/disk1/personal/huijuanz/ws/optimum-habana/optimum/habana/diffusers/pipelines/flux/pipeline_flux.py", line 372, in <genexpr>
    torch.zeros_like(guidance_batches[-1][0][None, :]) for _ in range(num_dummy_samples)
IndexError: too many indices for tensor of dimension 0

2024-12-13 10:08 UTC, huijuanzh commented
@regisss @dsocek  please help to review

2024-12-16 22:14 UTC, dsocek approved these changes
LGTM, thanks for the fix

2025-01-07 02:17 UTC, imangohari1 requested changes
I ran the test_diffusers.py with flux and all passed. 
also ran a flux example with README and it worked fine. 

It should be good to go after:
- rebase on the top of OH main. 
-  Apply the minor fixes in the attach patch with `git am < 0001*` 
[0001-make-style.patch](https://github.com/user-attachments/files/18326754/0001-make-style.patch)


Thanks.

2025-01-07 08:30 UTC, huijuanzh commented
> I ran the test_diffusers.py with flux and all passed. also ran a flux example with README and it worked fine.
> 
> It should be good to go after:
> 
> * rebase on the top of OH main.
> * Apply the minor fixes in the attach patch with `git am < 0001*`
>   [0001-make-style.patch](https://github.com/user-attachments/files/18326754/0001-make-style.patch)
> 
> Thanks.

@imangohari1  Done rebase and make-style, please help to review

2025-01-07 13:33 UTC, imangohari1 commented
@huijuanzh 
There has been mistake in the rebase. THere are now 110 files changed. Please properly merge OH main and force push your change. Tnx.

2025-01-08 01:15 UTC, huijuanzh commented
> @huijuanzh There has been mistake in the rebase. THere are now 110 files changed. Please properly merge OH main and force push your change. Tnx.

done merge with main branch

2025-01-09 00:19 UTC, imangohari1 approved these changes
LGTM! 
@regisss  please do a final review.

2025-01-17 16:00 UTC, regisss approved these changes

2025-01-17 16:00 UTC, merged