Fix for Mixtral G1 pytest failures
huggingface/optimum-habana pull request #1652
Opened 2024-12-20 16:43 UTC by 12010486

# What does this PR do?

**Fixes for the following pytests on Gaudi1:**

MixtralModelTest::test_contrastive_generate
MixtralModelTest::test_contrastive_generate_dynamic_shapes
MixtralModelTest::test_contrastive_generate_low_memory
MixtralModelTest::test_determinism
MixtralModelTest::test_feed_forward_chunking
MixtralModelTest::test_generate_from_inputs_embeds_decoder_only
MixtralModelTest::test_generate_without_input_ids
MixtralModelTest::test_greedy_generate
MixtralModelTest::test_left_padding_compatibility
MixtralModelTest::test_load_balancing_loss
MixtralModelTest::test_sample_generate 
MixtralModelTest::test_save_load MixtralModelTest::test_resize_embeddings_untied

**Modified the optimum/habana/utils.py**
Included Gaudi3 in get_device_name()

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests?

Tested on G1/G2/G3

2024-12-20 16:44 UTC, 12010486 commented
@libinta, @imangohari1, if you want to have a look

2024-12-23 10:44 UTC, regisss commented
@12010486 Is this PR different from #1654 ?

2024-12-23 10:48 UTC, 12010486 commented
No, it is basically the same, except for `make style` that here is included. However, I have not received confirmation yet on which PR to keep

2025-01-07 07:43 UTC, Silv3S approved these changes

2025-01-07 14:14 UTC, imangohari1 requested changes
@12010486 
Hi Silvia, 
Thanks for the PR. 
I have few suggestions:
- between #1652  and #1654, let's keep 1652 (aka this PR) since 1.15 is already released. We can closed the other one? 
- I think the logic in `gaudi_mixtral_block_moe_forward` can be simplified a bit. take a look at the suggestion I made and see if it fits. The idea is to only return the moe_forward when applicable and otherwise return the sparse. 
- In utils.py lin390, aka header of get_device_name(), please add "Returns the name of the current device: Gaudi, Gaudi2, or Gaudi3"

2025-01-07 14:14 UTC, imangohari1 commented on optimum/habana/transformers/models/mixtral/modeling_mixtral.py
> +    if not self.training and not os.environ.get("QUANT_CONFIG"):
```suggestion
    if self.training and os.environ.get("QUANT_CONFIG") and (get_device_name() == "gaudi2" or get_device_name() == "gaudi3")
        return self.sparse_moe_forward(hidden_states)
    
```

2025-01-10 22:58 UTC, imangohari1 commented
@12010486 
Hi Silvia, 
Can you look at the reviews here and update accordingly? thanks.

2025-01-14 15:19 UTC, 12010486 commented
Hi @imangohari1, can you have a look at it now? 
I agree with all your suggestions, but on point 2. I think the code you were suggesting is not exactly how it should be, so please, see how I modified it instead. Basically, at the moment the sparse_moe is still the default, unless the model is running inference on Gaudi2 or 3, and no compression.

2025-01-14 15:53 UTC, imangohari1 commented
> Hi @imangohari1, can you have a look at it now? I agree with all your suggestions, but on point 2. I think the code you were suggesting is not exactly how it should be, so please, see how I modified it instead. Basically, at the moment the sparse_moe is still the default, unless the model is running inference on Gaudi2 or 3, and no compression.

@12010486  
Hi Silvia, 
Thanks for the update. I think the code looks much cleaner now. I am going to do some testing on this and report back here. Thanks.

2025-01-14 17:36 UTC, imangohari1 reviewed
LGTM! 
I have ran pytests `https://github.com/12010486/optimum-habana/tree/mixtral-g1-failure` with and without this changes. Below are the results summary. These changes should be good. 
- G2: oh main and current pr have same results 
- G1: oh main has 13 extra failures that current PR does NOT listed below. 
```

=========================== short test summary info ============================
FAILED tests/transformers/tests/models/mixtral/test_modeling_mixtral.py::MixtralModelTest::test_Mixtral_sequence_classification_model_for_multi_label
FAILED tests/transformers/tests/models/mixtral/test_modeling_mixtral.py::MixtralModelTest::test_contrastive_generate
FAILED tests/transformers/tests/models/mixtral/test_modeling_mixtral.py::MixtralModelTest::test_contrastive_generate_dynamic_shapes
FAILED tests/transformers/tests/models/mixtral/test_modeling_mixtral.py::MixtralModelTest::test_contrastive_generate_low_memory
FAILED tests/transformers/tests/models/mixtral/test_modeling_mixtral.py::MixtralModelTest::test_determinism
FAILED tests/transformers/tests/models/mixtral/test_modeling_mixtral.py::MixtralModelTest::test_feed_forward_chunking
FAILED tests/transformers/tests/models/mixtral/test_modeling_mixtral.py::MixtralModelTest::test_generate_from_inputs_embeds_decoder_only
FAILED tests/transformers/tests/models/mixtral/test_modeling_mixtral.py::MixtralModelTest::test_generate_without_input_ids
FAILED tests/transformers/tests/models/mixtral/test_modeling_mixtral.py::MixtralModelTest::test_greedy_generate
FAILED tests/transformers/tests/models/mixtral/test_modeling_mixtral.py::MixtralModelTest::test_left_padding_compatibility
FAILED tests/transformers/tests/models/mixtral/test_modeling_mixtral.py::MixtralModelTest::test_load_balancing_loss
FAILED tests/transformers/tests/models/mixtral/test_modeling_mixtral.py::MixtralModelTest::test_sample_generate
FAILED tests/transformers/tests/models/mixtral/test_modeling_mixtral.py::MixtralModelTest::test_save_load
```

2025-01-20 17:25 UTC, regisss approved these changes

2025-01-20 17:25 UTC, merged