Add Llama test for fsdp
huggingface/optimum-habana pull request #761
Opened 2024-03-05 04:04 UTC by hlahkar

Add Llama test for FSDP

2024-03-05 04:07 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum-habana/pr_761). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-03-12 05:12 UTC, hlahkar commented
@regisss please review this test case. Our end goal is to test llama2; but we need to pass a auth token for that. We would like to know whether we can pass a token to the test case; in that case we can change the test from Llama to Llama2.

2024-03-14 04:57 UTC, greg-serochi commented on examples/language-modeling/README.md
> +  --deepspeed llama2_ds_zero3_config.json \
why is the deepspeed json file being called out here?

2024-03-14 05:51 UTC, vivekgoe requested changes

2024-03-14 05:51 UTC, vivekgoe commented on examples/language-modeling/README.md
> +```
FusedRoPE = false is missing.

2024-03-14 09:08 UTC, hlahkar commented on examples/language-modeling/README.md
> +```
Added

2024-03-15 09:39 UTC, regisss commented
> @regisss please review this test case. Our end goal is to test llama2; but we need to pass a auth token for that. We would like to know whether we can pass a token to the test case; in that case we can change the test from Llama to Llama2.

Yes that should be feasible. Take a look at how it is done in https://github.com/huggingface/optimum-habana/blob/main/tests/test_text_generation_example.py.
Basically your tests functions needs a `token` argument and you pass the token to pytest running:
```
pytest tests/test_fsdp_examples.py --token my_token
```
Let me know if that works.

2024-03-15 17:53 UTC, regisss approved these changes
LGTM!

I pushed a new commit to add the token arg in the CI command.

2024-03-15 18:35 UTC, regisss commented
@hlahkar When I run
```
pytest tests/test_fsdp_examples.py -v -s -k "llama" --token my_token
```
the test fails because the train loss is nan. Can you run it and see if you get the same please?

2024-03-16 10:04 UTC, hlahkar commented
@regisss on latest optimum-habana (after upgrade to transformer 4.38) this test is failing; prior to that this test was passing. Also this test need to be tested on Gaudi2 also is advisable to test this on 1.15 synapse release

2024-03-16 10:18 UTC, regisss commented
> @regisss on latest optimum-habana (after upgrade to transformer 4.38) this test is failing; prior to that this test was passing. Also this test need to be tested on Gaudi2 also is advisable to test this on 1.15 synapse release

On Synapse 1.15 does it pass?

2024-03-16 12:53 UTC, hlahkar commented
> > @regisss on latest optimum-habana (after upgrade to transformer 4.38) this test is failing; prior to that this test was passing. Also this test need to be tested on Gaudi2 also is advisable to test this on 1.15 synapse release
> 
> On Synapse 1.15 does it pass?

@regisss On Synapse 1.15 it passes with optimum-habana 1.10.4 + https://github.com/huggingface/optimum-habana/pull/753/files

But it fails with the latest optimum habana because of upgrade to transformers 4.38

2024-03-16 17:57 UTC, regisss commented
> > > @regisss on latest optimum-habana (after upgrade to transformer 4.38) this test is failing; prior to that this test was passing. Also this test need to be tested on Gaudi2 also is advisable to test this on 1.15 synapse release
> > 
> > 
> > On Synapse 1.15 does it pass?
> 
> @regisss On Synapse 1.15 it passes with optimum-habana 1.10.4 + https://github.com/huggingface/optimum-habana/pull/753/files
> 
> But it fails with the latest optimum habana because of upgrade to transformers 4.38

Okay. With Synapse 1.14 it fails even before the upgrade to Transformers 4.38.
Can you update your main branch and rebase this PR on it so that we can find a fix with the latest codebase?

2024-03-16 18:02 UTC, regisss commented
It works in fp32. There must be an operation between a bf16 and a fp32 somewhere that leads to nan.

2024-03-18 09:27 UTC, hlahkar commented
@regisss I tested the test case on top of latest optimum-habana + https://github.com/huggingface/optimum-habana/pull/812; the test is passing

2024-03-18 17:09 UTC, merged