Add Support for MT5 model on Gaudi2
huggingface/optimum-habana pull request #896
Opened 2024-04-17 09:44 UTC by Gaurav7888

Added Support for MT5 model on Gaudi2 using Static Shape Concept.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

2024-04-19 11:48 UTC, vivekgoe commented
@Gaurav7888 please check tests for translation using T5 here https://github.com/huggingface/optimum-habana/blob/main/tests/test_examples.py . Can you please add a test for MT5 also? Thanks.

2024-04-22 18:35 UTC, ssarkar2 requested changes
Please add tests and could you also mention the cmd line you used to test this in the PR

2024-05-07 17:27 UTC, libinta reviewed
@Gaurav7888  can you please address the comments?

2024-05-08 10:55 UTC, Gaurav7888 commented
@vivekgoe @ssarkar2 @libinta I have added the test files for mt5 model.

2024-05-08 16:22 UTC, ssarkar2 commented
@Gaurav7888 , there is a conflict that needs to be resolved. Please merge the latest main and your branch and resolve the conflicts

2024-05-10 17:54 UTC, libinta reviewed
@Gaurav7888  please provide the cmd test test in readme, also how is perf comparison with gpu?

2024-05-15 10:54 UTC, Gaurav7888 commented
@ssarkar2 I have made the changes and resolved the conflict. please review.

2024-06-13 19:54 UTC, libinta commented
@Gaurav7888  can you resolve the conflicts with main branch?

2024-06-19 11:13 UTC, Gaurav7888 commented
> @Gaurav7888 can you resolve the conflicts with main branch?

Please review it, I have made changes.

2024-07-09 20:04 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +        """
@Gaurav7888 same as above

2024-07-09 20:07 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +import warnings
@Gaurav7888 you have missed the header, which includes the model name and copyright

2024-07-09 20:13 UTC, yafshar commented
@Gaurav7888 please provide the test cmd in the README, also how is perf in comparison with gpu?

2024-07-09 20:48 UTC, yafshar commented
@Gaurav7888  Please also run make style

2024-07-09 20:54 UTC, yafshar commented on tests/transformers/tests/models/mt5/test_modeling_t5.py
> +torch_device = "hpu"
@Gaurav7888 why are you overwriting the `torch_device` it is already imported in L28. If this is for your own testing please remove it

2024-07-09 20:56 UTC, yafshar commented on tests/transformers/tests/models/mt5/test_modeling_t5.py
> +    def test_generate_with_past_key_values(self):
@Gaurav7888 this test is failing! Does it work correctly on your end. Please check

2024-07-09 21:02 UTC, yafshar commented on tests/transformers/tests/models/mt5/test_modeling_t5.py
> +    def test_generate_with_past_key_values(self):
Please fix the file name `test_modeling_t5.py` -> `test_modeling_mt5.py`

2024-07-12 10:53 UTC, Gaurav7888 commented
@yafshar  Hi, I have made the changes as requested. Please review

2024-07-12 16:13 UTC, yafshar commented
> @yafshar Hi, I have made the changes as requested. Please review

@Gaurav7888 thanks, please provide your test cmd?

2024-07-16 16:50 UTC, Gaurav7888 commented
@yafshar 

python run_translation.py \
    --model_name_or_path mt5-small \
    --do_eval \
    --source_lang en \
    --target_lang ro \
    --source_prefix "translate English to Romanian: " \
    --dataset_name wmt16 \
    --dataset_config_name ro-en \
    --output_dir /tmp/tst-translation \
    --per_device_eval_batch_size 4 \
    --overwrite_output_dir \
    --predict_with_generate \
    --use_habana \
    --use_lazy_mode \
    --use_hpu_graphs_for_inference \
    --gaudi_config_name Habana/t5 \
    --ignore_pad_token_for_loss False \
    --pad_to_max_length \
    --bf16

Is this you are asking? Please correct me.

2024-07-17 01:39 UTC, yafshar commented on tests/transformers/tests/models/mt5/test_modeling_t5.py
Please remove this file, it is irrelevant for mt5

2024-07-17 19:16 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +)
```suggestion
from transformers.utils import logging
```

2024-07-17 19:26 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +    FusedRMSNorm = None
```suggestion
try:
    from habana_frameworks.torch.hpex.normalization import FusedRMSNorm as FusedRMSNorm
    
    has_fused_rms_norm = True
except ImportError:
    has_fused_rms_norm = False
    print("Not using HPU fused kernel for RMSNorm")
```

2024-07-17 19:26 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +    if hidden_states.device.type == "hpu" and FusedRMSNorm:
```suggestion
    if hidden_states.device.type == "hpu" and has_fused_rms_norm:
```

2024-07-17 19:55 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +        """
```suggestion
        The only differences are:
        - add new args token_idx
        """
```

2024-07-17 20:03 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +        """
```suggestion
):
    """
```

There is an extra indentation in the whole function. Is there a reason for that, or just your api caused this. Please fix this extra indentation

2024-07-17 20:08 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +                hidden_states = past_key_value
```suggestion
            if past_key_value is not None:
                if key_value_states is None:
                    # self-attn
                    # (batch_size, n_heads, key_length, dim_per_head)
                    if token_idx is None:
                        hidden_states = torch.cat([past_key_value, hidden_states], dim=2)
                    else:
                        hidden_states = past_key_value.index_copy_(-2, token_idx - 1, hidden_states)
                elif past_key_value.shape[2] != key_value_states.shape[1]:
                    # checking that the `sequence_length` of the `past_key_value` is the same as
                    # the provided `key_value_states` to support prefix tuning
                    # cross-attn
                    # (batch_size, n_heads, seq_length, dim_per_head)
                    hidden_states = shape(proj_layer(key_value_states))
                else:
                    # cross-attn
                    hidden_states = past_key_value
```

Please ensure consistent indentation throughout the entire code.

2024-07-17 20:09 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +              real_seq_length = past_key_value[0].shape[2]
```suggestion
            if token_idx is None:
                real_seq_length += past_key_value[0].shape[2] if query_length is None else query_length
            else:
                real_seq_length = past_key_value[0].shape[2]
```

Please ensure consistent indentation throughout the entire code.

2024-07-17 20:12 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +                position_bias = position_bias.index_select(-2, token_idx - 1)
```suggestion
            if past_key_value is not None:
                if token_idx is None:
                    position_bias = position_bias[:, :, -hidden_states.size(1) :, :]
                else:
                    position_bias = position_bias.index_select(-2, token_idx - 1)
```

Please ensure consistent indentation throughout the entire code.

2024-07-17 20:18 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +    """
```suggestion
    The only differences are:
    - add new args token_idx
    """
```

2024-07-17 20:30 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +    ):
```suggestion
    ):
    """
    The only differences are:
    - add new args token_idx
    """
```

2024-07-17 20:33 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +            if not self.is_decoder:
```suggestion
    if past_key_value is not None:
        if not self.is_decoder:
```
Please ensure consistent indentation throughout the entire code.

2024-07-17 21:47 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +        use_cache = use_cache if use_cache is not None else self.config.use_cache
```suggestion
    ):
    """
    The only differences are:
    - add new args token_idx
    """
    use_cache = use_cache if use_cache is not None else self.config.use_cache
```

There is an extra indentation in this function!
Please ensure consistent indentation throughout the entire code.

2024-07-17 22:00 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +        if use_cache is True:
```suggestion
        if use_cache:
```

2024-07-17 22:00 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +            if use_cache is False:
```suggestion
            if not use_cache:
```

2024-07-17 22:10 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +
```suggestion
:
    """
    The only differences are:
    - add new args token_idx
    """

```

2024-07-17 22:17 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +):
```suggestion
    ):
    """
    The only differences are:
    - add new args token_idx
    """
```

2024-07-17 22:23 UTC, yafshar commented
> @yafshar
> 
> python run_translation.py --model_name_or_path mt5-small --do_eval --source_lang en --target_lang ro --source_prefix "translate English to Romanian: " --dataset_name wmt16 --dataset_config_name ro-en --output_dir /tmp/tst-translation --per_device_eval_batch_size 4 --overwrite_output_dir --predict_with_generate --use_habana --use_lazy_mode --use_hpu_graphs_for_inference --gaudi_config_name Habana/t5 --ignore_pad_token_for_loss False --pad_to_max_length --bf16
> 
> Is this you are asking? Please correct me.

@Gaurav7888 do you have the GPU performance number on A100 or others?

I was able to run with minor modification `--model_name_or_path google/mt5-small`

2024-07-17 22:39 UTC, yafshar commented
This is what I currently get
```python
>> python run_translation.py --model_name_or_path google/mt5-small --do_eval --source_lang en --target_lang ro --source_prefix "translate English to Romanian: " --dataset_name wmt16 --dataset_config_name ro-en --output_dir /root/tst-translation --per_device_eval_batch_size 4 --overwrite_output_dir --predict_with_generate --use_habana --use_lazy_mode --use_hpu_graphs_for_inference --gaudi_config_name Habana/t5 --ignore_pad_token_for_loss False --pad_to_max_length --bf16

***** eval metrics *****
  eval_bleu                   =     0.0034
  eval_gen_len                =      127.0
  eval_loss                   =    51.5938
  eval_runtime                = 0:01:22.44
  eval_samples                =       1999
  eval_samples_per_second     =     24.247
  eval_steps_per_second       =      6.065
  max_memory_allocated (GB)   =       2.65
  memory_allocated (GB)       =       2.65
  total_memory_available (GB) =      94.62
```

2024-07-17 22:41 UTC, yafshar commented on optimum/habana/transformers/models/t5/modeling_t5.py
Please revert this commit. Irrelevant for mt5

2024-07-25 18:34 UTC, yafshar commented
@Gaurav7888 can you address the comment to finish this PR?

2024-08-05 08:34 UTC, Gaurav7888 commented on optimum/habana/transformers/models/t5/modeling_t5.py
> +
```suggestion
```

2024-08-06 13:56 UTC, Gaurav7888 commented
> @Gaurav7888 can you address the comments to finish this PR?

I have done the changes, please check

2024-08-07 14:11 UTC, yafshar commented
@Gaurav7888 I will check the latest changes

2024-09-09 16:42 UTC, yafshar commented on optimum/habana/transformers/models/mt5/modeling_mt5.py
> +    from habana_frameworks.torch.hpex.normalization import FusedRMSNorm as FusedRMSNorm
```suggestion
    from habana_frameworks.torch.hpex.normalization import FusedRMSNorm

```

2024-09-09 19:29 UTC, yafshar commented
@Gaurav7888 there are `IndentationError` introduced by unexpected indentation in the code. Please check and fix them

2024-09-19 18:16 UTC, yafshar commented
@Gaurav7888 would you please address the comment to wrap up this PR

2024-09-24 15:56 UTC, yafshar commented
@Gaurav7888 any update?

2024-11-14 23:07 UTC, libinta commented
@Gaurav7888  I am closing the PR as no response

2024-11-14 23:07 UTC, closed without merging