Fix for the simulate_dyn_prompt flag assertion
huggingface/optimum-habana pull request #984
Opened 2024-05-15 12:27 UTC by alekseyfa

# What does this PR do?

This PR fixes an error that occurred when the `--dataset_name` flag was set. 

```bash
AssertionError: Both dataset_name and simulate_dyn_prompt are set
```

The `assert args.simulate_dyn_prompt == ""` never passed because `None` was compared to an empty string.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

2024-05-15 19:08 UTC, ssarkar2 approved these changes

2024-05-15 19:13 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum-habana/pr_984). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-05-15 21:57 UTC, MohitIntel approved these changes
I tested this change with the command:
python run_generation.py --model_name_or_path gpt2 --batch_size 2 --max_new_tokens 100 --use_hpu_graphs --use_kv_cache --dataset_name JulesBelveze/tldr_news --column_name content --bf16 --simulate_dyn_prompt 25 35 45

The fix works correctly and throws the assertion. Without the fix, the assertion was being thrown wrongly (even when not using --simulate_dyn_prompt 25 35 45).

2024-05-15 22:45 UTC, ssarkar2 requested changes
@alekseyfa , can you also make this readme fix in this section:
https://github.com/huggingface/optimum-habana/tree/main/examples/text-generation#using-growing-bucket-optimization

`For example --simulate_dyn_prompt 25,35,45`
this should be: `For example --simulate_dyn_prompt 25 35 45`

Its used correctly at the end of the para:
`Thus the suggested configuration to simulate dynamicity after warmup is to use all three arguments: --simulate_dyn_prompt 25 35 45 --reduce_recompile --bucket_size 30`

2024-05-16 09:34 UTC, alekseyfa commented
> @alekseyfa , can you also make this readme fix in this section: https://github.com/huggingface/optimum-habana/tree/main/examples/text-generation#using-growing-bucket-optimization
> 
> `For example --simulate_dyn_prompt 25,35,45` this should be: `For example --simulate_dyn_prompt 25 35 45`
> 
> Its used correctly at the end of the para: `Thus the suggested configuration to simulate dynamicity after warmup is to use all three arguments: --simulate_dyn_prompt 25 35 45 --reduce_recompile --bucket_size 30`

 @ssarkar2 Done

2024-05-16 17:22 UTC, ssarkar2 approved these changes

2024-05-17 09:52 UTC, regisss approved these changes

2024-05-17 09:52 UTC, merged